### ISSUE TITLE
ソートできないです

### ISSUE THREAD

**Issue by rinabouk** [masaki-cb/crocus#1]
ありがとうございます！
すみません、issueに書かせていただきます
Q1ではソートできるのですが、他のQ、および曲名、演奏名、人でもソートできないようです。ご確認いただけますでしょうか

**Comment by rinabouk** [comment]
すみません、事象が異なりました。

webにアクセスして、最初に何かの項目でソートしたいときは、どの項目でもソートができます。たとえばQ3でソートしたとします。
その後、それ(Q3)以外の項目で改めてソートしようとすると、ソートできません
で、さらに、もう一回Q3でソートしようとすると、1回は正しくソートできるのですが、2回目はおかしな順番(デフォルトに戻った？)で並んで、3回目以降ソートできなくなります。

**Comment by rinabouk** [comment]
曲名、演奏名、人のソートは、順番にソートができるが、Qをソートすると上記挙動が出るようです

**Comment by hotsukai** [comment]
issueのほうありがとうございます。
ソートの実装がおかしいこと確認しました。
修正したらまたお知らせします。

**Comment by rinabouk** [comment]
ありがとうございます！

あとこれは、もはや好みの問題なので、難しければ無視していただいて大丈夫なのですが・・・


各列のソートのために押すアイコン(上むきの三角と下向きの三角が並んでいる)が、各列の右のアイコンなのか左のアイコンなのかが少しわかりにくいです
添付は「読みやすいと思いますか？」を正しく右のアイコンを押してソートできているスクショですが、最初左を押してしまいました。。。
<img width="183" alt="スクリーンショット 2021-06-11 23 20 12" src="https://user-images.githubusercontent.com/2150310/121701275-b2d03380-cb0b-11eb-8df8-1484c518fc3a.png">


各列の左側に少し余白が出るようにするなどして、どこが列の切れ目かがわかりやすいようにできますでしょうか？
繰り返しですが、もしも可能であれば、で問題ありません。。。

**Comment by rinabouk** [comment]
ごめんなさい！！！これ、Qの日本語をクリックするだけでソートできますね！これで問題ないですありがとうございます！！！！！

**Comment by rinabouk** [comment]
もしかして修正してくださいましたねありがとうございます・・・

**Comment by rinabouk** [comment]
<img width="873" alt="スクリーンショット 2021-06-12 22 41 23" src="https://user-images.githubusercontent.com/2150310/121777936-7b2abf80-cbcf-11eb-9848-14b195cc4431.png">

ごめんなさい、私の操作がおかしいのかもしれませんが、小数点の桁が違うせいで？ソートが一部変なところがありそうです。
「読みやすいと思いますか？」の6とか6.5とか6.25とかの並び順がおかしいのがお分かりいただけますでしょうか？文字列でのソートになっているのでしょうか？(ソートって思い通りにいかないですよね、、、)

**Comment by hotsukai** [comment]
文字列ソートになってますね..
数字のソートに修正します...!気づかなかった指摘ありがとうございます！！

**Comment by hotsukai** [comment]
修正されたと思うので確認いただけると幸いです。

**Comment by rinabouk** [comment]
ありがとうございます！！！！

**Comment by rinabouk** [comment]
マルチソートがシフトキーを押した時で実装できるとは想像していませんでした！！！！ありがとうございます！！！たのしー
