### ISSUE TITLE
各Qの説明加えていただけますでしょうか

### ISSUE THREAD

**Issue by rinabouk** [masaki-cb/crocus#2]
(問1)読みやすいと思いますか？(10:読みやすい-0:読みにくい)
(問2)わかりやすいと思いますか？(10:わかりやすい-0:わかりにくい)
(問3)今後の演奏に役に立つと思いますか？(10:役に立つ-0:役に立たない)
(問4)今後の演奏に関連しない記載があると思いますか？(10:関連しない記載はない-0:関連しない記載がある)
(問5)曖昧な記載だと思いますか？(10:曖昧でない-0:曖昧である)
(問6)今後の演奏に関連する記載が全て書かれていると思いますか？(10:書かれている-0:書かれていない)
(問7)矛盾がないと思いますか？(10:矛盾はない-0:矛盾がある)
(問8)記載されている内容は演奏を聴くことで検証できると思いますか？(10:検証できる-0:検証できない)
(問9)記載されている内容から該当箇所を楽譜で参照できると思いますか？(10:参照できる-0:参照できない)

**Comment by hotsukai** [comment]
issueありがとうございます。
実装しますね。

**Comment by rinabouk** [comment]
ありがとうございます！！！！このissueはcloseさせていただきます！
