### ISSUE TITLE
レイアウト：好みなので無視していただいて大丈夫ですが

### ISSUE THREAD

**Issue by rinabouk** [masaki-cb/crocus#3]
ソートの結果について、もう少し多く見せてもいいのではないかと思いました。
下の方に出てくるpdfの左側が余白なのがもったいない、というニュアンスで伝わりますでしょうか・・・

添付のひだ左下がもったいないよね、ということです
<img width="1286" alt="スクリーンショット 2021-06-11 15 44 42" src="https://user-images.githubusercontent.com/2150310/121642816-fc992980-cacb-11eb-817a-148a3259f1ad.png">

**Comment by hotsukai** [comment]
#1 #2 #3 を反映してデプロイしました。
https://masaki-cb.github.io/mpcdb/ を確認いただきたいです。

**Comment by rinabouk** [comment]
ありがとうございます！！！！このissueはcloseさせていただきます。
追伸： ポートフォリオ拝見させていただきました。大変お忙しいところお力添えいただいておりますこと感謝申し上げます。
