### ISSUE TITLE
あるといいかもしれない機能

### ISSUE THREAD

**Issue by hotsukai** [masaki-cb/crocus#4]
思いつきで書いているのでお時間があるときに要不要の判断をいただけると幸いです。

- グラフ描画
  - Q1~9それぞれのグラフがあり、選択された批評がハイライトされるイメージ
- URLを共有した際に選択された批評が引き継がれる
- 表の行をフィルタリングできる。
  - グラフを作る場合はフィルタリング結果に該当する場所は控えめにハイライトされる
- サイトのタイトルやdescriptionを本番運用できるように修正する

**Comment by rinabouk** [comment]
こちら気づくのが遅くなり申し訳ありません

グラフ描画
Q1~9それぞれのグラフがあり、選択された批評がハイライトされるイメージ
>あったらとても面白いなと思います！
ページ全体としての見やすさは要検討だと思いますが（情報が多くなりすぎてどこを見ればいいのかわからなくなることがないように)


URLを共有した際に選択された批評が引き継がれる
＞面白いですね。


表の行をフィルタリングできる。
グラフを作る場合はフィルタリング結果に該当する場所は控えめにハイライトされる
＞Q1が5以上だけ見る、みたいなイメージでしょうか？
面白い・・・です・・・


サイトのタイトルやdescriptionを本番運用できるように修正する
＞これだけは必須かもしれません
是非、と思うところですが、具体的にどういうタイトルが良いのか@masaki-cb 先生のお考えを仰ぎたいです。
zenodoのページと表題が異なるのは意図的でしょうか？
あと、作成者の情報、zenodoへのリンクは入れた方がいいでしょうか。(何をどこまで入れるかは@masaki-cb 先生のご指示に従いたいと思います)



以下は、実はソートの挙動を直していただいたときに逆に外れてしまった機能で、
そして見た目をnoisyにせずにどう実装するかは私もアイデアはないのですが
複数条件でのソートをしたい人はいるかなとは思いました。ただ必須ではないかと思います。
（ソートするたびに、デフォルトの並び順を基準としたソートになるようですね？）

**Comment by masaki-cb** [comment]
いろいろ提案してくれてありがとう！

> ・グラフ描画
>  Q1~9それぞれのグラフがあり、選択された批評がハイライトされるイメージ

いぞぎではないですが，いずれ欲しい機能と思いました．
9つのグラフ（Q1〜Q9）：239文書のQのスコアの棒グラフ（高い順にソート）があって，選択された批評がどの順位に位置するか棒グラフ上でハイライトされる

> URLを共有した際に選択された批評が引き継がれる

これの応用イメージがつかめず．他の人に批評が選択された状態で渡せる，というメリットを狙ってますか？
意外とあると便利かもしれない．実装も簡単そうならあると良さそう．急ぎではない．

> 表の行をフィルタリングできる。
> グラフを作る場合はフィルタリング結果に該当する場所は控えめにハイライトされる

良いですね．これも実装が簡単そうなら欲しい．急ぎではない．
@rinaboukさんの複数条件でのソートもあると良いですね．今は他のソートをクリックすると現在のソートは解除されますが，
クリックするとソートを指定・解除になると良いのかな．

> サイトのタイトルやdescriptionを本番運用できるように修正する

これは優先度高めです．
私や@rinaboukさんが編集しやすいようにしてもらえると@hotsukaiさんに作業依頼しなくていいものはこちらで作業できると思います．


上記以外で思い当たる修正点としては
・スコアの値は小数点1位までで四捨五入する

です．もしお時間ありましたら．

**Comment by rinabouk** [comment]
(1)スコアの値は小数点3位までで四捨五入する(1位までだと同じ値が並ぶところが出てきそうです)
(2)サイトのタイトルやdescriptionを本番運用できるように修正(作成者の情報、zenodoへのリンクなども必要があれば)

ここは(のんびりファイルを見直して時間さえかければ)できそうですね、やりましょう。(他の機能の実装は私にはちょっと無理だと思います。。。)
・・・で、(2)での名前はどうされますか？@masaki-cb

**Comment by masaki-cb** [comment]
(1)は@hotsukaiくんに小数点0位〜3位までのバージョンを作ってもらって見た目を確認したのですが，数字が煩くない＆ソートした時に被りが少ない，のトレードオフを考慮して小数点第1位で，となりました．数の被りは多少あった方が現実的なのと，内部的には細かい値でソートしているので，問題ないかと．

講評文に何点，と点数つける時も10点満点かせいぜい100点満点だろうということで，第1位が妥当ではないかと思います．
演奏を評価するアプリとかでも小数点第1位のものが多いので．

**Comment by rinabouk** [comment]
グラフも可愛いですね。

**Comment by rinabouk** [comment]
すみません、香川のページのリンクをメンバー一覧に差し込んでいただけますでしょうか。松原先生のリンクのようなイメージです。
自分でやろうとしたのですが、すみません、どこを見ればいいのかわからず。。。申し訳ありません。こんなことで。。。

https://sites.google.com/view/rinabou/home/CV_Japanese

追伸：英語版ありがとうございました！

**Comment by hotsukai** [comment]
@rinabouk 
ページリンク差し込みの件承知しました。
今後もなにか改善したい点があればお気になさらず、気軽に教えていただきたいです。

**Comment by hotsukai** [comment]
@rinabouk 

対応しました。
ご都合が良いときに確認よろしくおねがいします。
https://masaki-cb.github.io/crocus/

**Comment by rinabouk** [comment]
対応早すぎ。。。該当ファイルがうまく見つけられずご迷惑おかけいたしました。
